[package]
name = "Boid-Simulation_Rust"
version = "0.1.0"
edition = "2024"

[dependencies]
macroquad = "0.4"
egui = "0.27"
egui-macroquad = "0.17"
csv = "1.3"
serde = { version = "1.0", features = ["derive"] }