[package]
name = "Boid-Simulation_Rust"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3.1"
egui = "0.32.0"
glam = "0.30.5"
macroquad = "0.4.14"
rand = "0.9.2"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
