[package]
name = "New-Gray-Scott"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.28"
egui = "0.28"
rand = "0.8"
pixels = "0.13.0"
winit = "0.29.0"
rayon = "1.8.0"


[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"