[package]
name = "Gray-Scott"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.27"
egui = "0.27"
egui_plot = "0.27"
rayon = "1.7"
fastrand = "1"
csv = "1.3"
serde = { version = "1.0", features = ["derive"] }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1