[package]
name = "fractal-simulator"
version = "0.1.0"
edition = "2021"

[dependencies]
pixels = "0.13"
winit = "0.28"
env_logger = "0.11"
log = "0.4"
rayon = "1.10"
wide = { version = "0.7", optional = true }

[features]
default = []
simd = ["wide"]
